version: "3.2"
services:
  app:
    image: opendialogai/opendialog:1.x
    restart: on-failure
    tty: true
    ports:
      - "80:80"
      - "4443:443"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app-network
    depends_on:
      - mysql
      - dgraph-server
      - dgraph-zero
  mysql:
    image: mysql:5.7.27
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: opendialog
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: opendialog
      MYSQL_PASSWORD: opendialog
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
  dgraph-zero:
    image: dgraph/dgraph:v21.03.0-12-g44005bc82
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=dgraph-zero:5080
    networks:
      - app-network
    links:
      - dgraph-server
  dgraph-server:
    image: dgraph/dgraph:v21.03.0-12-g44005bc82
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --security token=dgraphauthsecrettoken --security whitelist=0.0.0.0/0 --my=dgraph-server:7080 --zero=dgraph-zero:5080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  appdata:
  dbdata:
    driver: local
  dgraph:
